### ISSUE TITLE
Coordinator withdrawMGNandDepositsFromBothPools does not work

### ISSUE THREAD

**Issue by W3stside** [gnosis/dx-mgn-pool#82]
/cc @josojo @fleupold @bh2smith 

`@gnosis.pm/dx-mgn-pool@0.1.3-RC2`
Function for reference:
```
function withdrawMGNandDepositsFromBothPools() public {
        address(dxMgnPool1).delegatecall(abi.encodeWithSignature("withdrawDeposit()"));
        address(dxMgnPool1).delegatecall(abi.encodeWithSignature("withdrawMagnolia()"));

        address(dxMgnPool2).delegatecall(abi.encodeWithSignature("withdrawDeposit()"));
        address(dxMgnPool2).delegatecall(abi.encodeWithSignature("withdrawMagnolia()"));
    }
```

Intended behaviour:
1. Function calls all 4 functions from DxMgnPool @dxMgn1 address and @dxMgn2 address, respectively.
2. Function returns a tx receipt
3. Contract state is changed/written + reflected in the FE

Actual behaviour:
1. Unknown whether the `Coordinator` contract actually `delegateCall`s the necessary functions
2. tx receipt IS returned, but the data is hard/impossible to debug as successful or not
3. Contract state is NOT apparently changed/written - FE does NOT show any changes

Possible reason(s):
1. `delegateCall` is not properly coded out yet to throw the necessary error(s), if any, so `withdrawMGNandDepositsFromBothPools` ignores errors and returns a tx receipt without throwing and stopping code executions. This would explain the txReceipt coming through but no state change happening

**Comment by Velenir** [comment]
To demonstarate this behavior gnosis/dx-mgn-pool-react#7

**Comment by josojo** [comment]
Thanks for creating it. @W3stside 

I will look into it. Do I understand it correctly that tokens are withdrawn and but not the MGN[ gnosis/dx-mgn-pool-react#7 seems to imply it] or is really no withdrawn done and no balances are changed?

**Comment by Velenir** [comment]
Nothing is withdrawn

If I understand how `delegatecall` works, it calls the function from another contract but with the callee contract's `this` and storage and the original `msg.sender`. Like `dxMgnPool.withdrawMagnolia.call(Coordinator instance)` would work if it were JS
So `withdrawMagnolia` tries to work with Coordinator's storage and fails.

Am I correct @josojo ?

**Comment by josojo** [comment]
Uh, yeah you are right @Velenir. That is the only reason the proxy contracts can work how they are working. I will try to fix it quickly by using another solution.

**Comment by josojo** [comment]
Okay, I can think of two solutions:

1. solution
Currently we have:
`
function withdrawDeposit() public returns(uint) 
function withdrawMagnolia() public returns(uint)
`
And we can add:
`
function withdrawDepositandMagnolia() public returns(uint, uint){
return (withdrawDeposit(),withdrawMagnolia())
}
`
If we implement this solution, only one call per pool is needed instead of 2
However, we need for two pools two calls - with the coordinator solution we would have only needed 1.

2. solution
We create special rights for the Coordinator contract in the pool to withdraw on behalve of the users. This would requrie to do major refactoring. I would have to create two more functions:
`
function withdrawDepositFromCoordinator(address sender) public returns(uint) 
function withdrawMagnoliaFromCoordinator(address sender) public returns(address sender)
`

Considering that the code was already audited, I suggest to only go ahead with the first solution, as it does not really change any code and will not introduce bugs.

Is solution 1 sufficient? @W3stside @Velenir @christianee

**Comment by W3stside** [comment]
@josojo I'm happy with solution 1 until such time that we can refactor and run with solution 2. 

Right now in the FE we are recreating your solution 1 via 2 calls to the respective functions, so having this reduced in half would be a nice add for sure. 

If you could please go with solution 1 then add @Velenir and I as reviewers that'd be great. Thanks Alex

**Comment by josojo** [comment]
Good, I will definitely implement solution 1.

But I am not sure whether we want to implement the second solution, due to error risks and need for second contract audit?
If the only disadvantage is two transactions instead of 1, I recommend not going for it.
